SITE_URL = "http://127.0.0.1:8000/"
#SESSION_COOKIE_DOMAIN = SITE_URL
STATIC_URL_FULL_PATH = SITE_URL + "static/"
STRIPE_PUBLIC_KEY = os.environ.get('DEV_STRIPE_KEY')
STRIPE_SECRET_KEY = os.environ.get('DEV_STRIPE_SECRET')
